[datasets]
[datasets.M5]
url = "https://raw.githubusercontent.com/MaximeLutel/streamlit_prophet_datasets/main/M5.csv"
date = "date"
target = "sales"
[datasets.SAV]
url = "https://raw.githubusercontent.com/MaximeLutel/streamlit_prophet_datasets/main/SAV.csv"
date = "ds"
target = "target"
[datasets.Weather]
url = "https://raw.githubusercontent.com/MaximeLutel/streamlit_prophet_datasets/main/weather.csv"
date = "datetime"
target = "temperature"

[model]
seasonality_prior_scale = 10
holidays_prior_scale = 10
regressors_prior_scale = 10
changepoint_prior_scale = 0.050
growth = ['linear', 'logistic']
seasonality_mode = ['additive', 'multiplicative']
n_changepoints = 25
changepoint_range = 0.80

[style]
colors = ["#002244", "#ff0066", "#66cccc", "#ff9933", "#337788", "#429e79", "#474747", "#f7d126", "#ee5eab", "#b8b8b8"]
color_axis = '#d62728'

[global]
seed = 42
